modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="${loader_version_range}" #mandatory
license="ARR"
[[mods]] #mandatory
# The modid of the mod
modId="smoothmovement" #mandatory
version="${mod_version}" #mandatory
displayName="smoothmovement mod" #mandatory
authors="Someaddon" #optional
description='''
smoothmovement mod
'''
[[dependencies.smoothmovement]]
modId="minecraft"
mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[1.21,1.30)"
ordering="NONE"
side="BOTH"
[[dependencies.smoothmovement]]
modId="cupboard"
mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[1.21-1.4,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="smoothmovement.mixins.json"